import { useEffect, useRef, useState } from "react";
import { motion } from "framer-motion";
import { ArrowLeft, Check, Sparkles, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { PolicySearchStep, type PolicyItem } from "@/components/policy-drafting/drafting/PolicySearchStep";
import { PolicyAnalysisStep, type ClauseComparison } from "@/components/policy-drafting/drafting/PolicyAnalysisStep";
import { OutlineGenerationStep, ReferenceDocPanel, type OutlineSection } from "@/components/policy-drafting/drafting/OutlineGenerationStep";
import { PolicyOutputPage } from "@/components/policy-drafting/drafting/PolicyOutputPage";
import { generateCoreElements } from "@/lib/policyDraftApi";

const flowSteps = [
  { id: 1, label: "输入政策标题" },
  { id: 2, label: "政策检索" },
  { id: 3, label: "政策对比分析" },
  { id: 4, label: "大纲生成" },
  { id: 5, label: "政策编辑" },
];

interface PolicyDraftingFlowProps {
  onBack: () => void;
  initialTitle?: string;
  initialCoreElements?: string;
  autoGenerateInitialCoreElements?: boolean;
}

export function PolicyDraftingFlow({
  onBack,
  initialTitle,
  initialCoreElements,
  autoGenerateInitialCoreElements = false,
}: PolicyDraftingFlowProps) {
  const [currentStep, setCurrentStep] = useState(1);
  /** 已完成（訪問過）的最大步驟，用於控制步驟條可點擊範圍 */
  const [maxReachedStep, setMaxReachedStep] = useState(1);
  const [title, setTitle] = useState(initialTitle || "");
  const [coreElements, setCoreElements] = useState(initialCoreElements || "");
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedPolicies, setSelectedPolicies] = useState<PolicyItem[]>([]);
  const [analysisResult, setAnalysisResult] = useState<ClauseComparison[]>([]);
  const [outlineResult, setOutlineResult] = useState<OutlineSection[]>([]);
  const [draggingDocTitle, setDraggingDocTitle] = useState<string | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  const handleAiGenerate = async () => {
    if (!title.trim()) return;
    setIsGenerating(true);
    try {
      const { coreElements: result } = await generateCoreElements(title);
      setCoreElements(result);
    } catch {
      setCoreElements(
        "1. 政策适用范围与对象\n2. 扶持标准与补贴金额\n3. 申报条件与流程\n4. 资金来源与保障措施\n5. 监督管理与绩效评估"
      );
    } finally {
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    if (!autoGenerateInitialCoreElements || !initialTitle || initialCoreElements || hasAutoGeneratedRef.current) {
      return;
    }

    hasAutoGeneratedRef.current = true;
    setIsGenerating(true);

    generateCoreElements(initialTitle)
      .then(({ coreElements: result }) => {
        setCoreElements(result);
      })
      .catch(() => {
        setCoreElements(
          "1. 政策适用范围与对象\n2. 扶持标准与补贴金额\n3. 申报条件与流程\n4. 资金来源与保障措施\n5. 监督管理与绩效评估"
        );
      })
      .finally(() => setIsGenerating(false));
  }, [autoGenerateInitialCoreElements, initialCoreElements, initialTitle]);

  const goNext = () => {
    if (currentStep < 5) {
      const next = currentStep + 1;
      setCurrentStep(next);
      setMaxReachedStep(prev => Math.max(prev, next));
    }
  };

  const goBack = () => {
    if (currentStep > 1) setCurrentStep(prev => prev - 1);
  };

  /** 點擊步驟條跳轉：只允許跳到已訪問過的前序步驟 */
  const handleStepClick = (stepId: number) => {
    if (stepId < currentStep && stepId <= maxReachedStep) {
      setCurrentStep(stepId);
    }
  };

  // Step 5: Full-page editor
  if (currentStep === 5) {
    return (
      <div className="flex-1 flex flex-col min-h-0">
        <PolicyOutputPage
          policyTitle={title}
          coreElements={coreElements}
          selectedPolicies={selectedPolicies}
          outline={outlineResult}
          onBack={() => setCurrentStep(4)}
        />
      </div>
    );
  }

  /** 步驟條底部按鈕列：左側返回 + 右側下一步 */
  const renderBottomActions = (nextLabel: string, nextDisabled = false) => (
    <div className="flex items-center gap-3 pt-2">
      {currentStep > 1 && (
        <Button
          variant="outline"
          onClick={goBack}
          className="h-11 px-5 text-sm font-medium flex items-center gap-1.5 shrink-0"
        >
          <ArrowLeft className="h-4 w-4" />
          返回上一步
        </Button>
      )}
      <Button
        onClick={goNext}
        disabled={nextDisabled}
        className="flex-1 h-11 gov-gradient text-primary-foreground hover:opacity-90 transition-opacity text-sm font-medium"
      >
        {nextLabel}
      </Button>
    </div>
  );

  return (
    <div className="space-y-5">
      {/* Back to home */}
      <button
        onClick={onBack}
        className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
      >
        <ArrowLeft className="h-4 w-4" />
        返回首页
      </button>

      {/* Flow stepper — 前序已訪問步驟可點擊 */}
      <div className="flex items-center justify-center gap-0 mb-2">
        {flowSteps.map((step, i) => {
          const isCompleted = currentStep > step.id;
          const isCurrent = currentStep === step.id;
          const isClickable = step.id < currentStep && step.id <= maxReachedStep;

          return (
            <div key={step.id} className="flex items-center">
              <div className="flex items-center gap-2">
                <div
                  onClick={() => handleStepClick(step.id)}
                  className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-semibold shrink-0 transition-all
                    ${isCompleted ? "gov-gradient text-primary-foreground" : ""}
                    ${isCurrent ? "border-2 border-primary text-primary bg-primary/10" : ""}
                    ${!isCompleted && !isCurrent ? "bg-muted text-muted-foreground" : ""}
                    ${isClickable ? "cursor-pointer hover:opacity-80 ring-2 ring-primary/30 ring-offset-1" : "cursor-default"}
                  `}
                >
                  {isCompleted ? <Check className="h-3.5 w-3.5" /> : step.id}
                </div>
                <span
                  onClick={() => handleStepClick(step.id)}
                  className={`text-xs font-medium whitespace-nowrap transition-colors
                    ${isCurrent ? "text-primary" : ""}
                    ${isCompleted ? "text-foreground" : ""}
                    ${!isCompleted && !isCurrent ? "text-muted-foreground" : ""}
                    ${isClickable ? "cursor-pointer hover:text-primary underline-offset-2 hover:underline" : "cursor-default"}
                  `}
                >
                  {step.label}
                </span>
              </div>
              {i < flowSteps.length - 1 && (
                <div
                  className={`w-12 h-[2px] mx-3 transition-colors ${
                    currentStep > step.id ? "bg-primary" : "bg-border"
                  }`}
                />
              )}
            </div>
          );
        })}
      </div>

      {/* Step content（Step 4 雙欄佈局需跳出 max-w 限制，單獨處理） */}
      <motion.div
        key={currentStep}
        initial={{ opacity: 0, x: 16 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.25 }}
        className={currentStep === 4 ? "" : "max-w-4xl mx-auto"}
      >
        {/* Step 1: Input */}
        {currentStep === 1 && (
          <div className="bg-card rounded-xl border border-border p-6 space-y-6">
            <div>
              <h2 className="text-lg font-semibold text-foreground mb-1">补充政策信息</h2>
              <p className="text-sm text-muted-foreground">请填写政策相关信息，AI 将根据信息智能检索并生成政策初稿</p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="policy-title" className="text-sm font-medium">
                政策标题 <span className="text-primary">*</span>
              </Label>
              <Input
                id="policy-title"
                placeholder="请输入政策标题，例如：关于促进新一代信息技术产业发展的若干政策"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="h-11"
              />
            </div>

            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label htmlFor="core-elements" className="text-sm font-medium">
                  核心要素
                  <span className="text-muted-foreground font-normal ml-1.5">（选填）</span>
                </Label>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleAiGenerate}
                  disabled={isGenerating}
                  className="h-7 px-2.5 text-xs gap-1.5 border-primary/30 text-primary hover:bg-primary/5 hover:text-primary"
                >
                  <Sparkles className="h-3.5 w-3.5" />
                  {isGenerating ? "生成中..." : "AI 生成"}
                </Button>
              </div>
              <Textarea
                id="core-elements"
                placeholder="请输入政策核心要素，或点击「AI 生成」自动填充"
                value={coreElements}
                onChange={(e) => setCoreElements(e.target.value)}
                className="min-h-[140px] resize-none"
              />
            </div>

            <Button
              onClick={goNext}
              disabled={!title.trim()}
              className="w-full h-11 gov-gradient text-primary-foreground hover:opacity-90 transition-opacity text-sm font-medium"
            >
              下一步：政策检索
            </Button>
          </div>
        )}

        {/* Step 2: Policy Search */}
        {currentStep === 2 && (
          <div className="bg-card rounded-xl border border-border p-6 space-y-6">
            <PolicySearchStep
              policyTitle={title}
              coreElements={coreElements}
              policies={selectedPolicies}
              onPoliciesSelected={setSelectedPolicies}
            />
            {renderBottomActions(
              `下一步：政策对比分析（已选 ${selectedPolicies.filter(p => p.selected).length} 条）`,
              selectedPolicies.filter(p => p.selected).length === 0
            )}
          </div>
        )}

        {/* Step 3: Policy Analysis */}
        {currentStep === 3 && (
          <div className="bg-card rounded-xl border border-border p-6 space-y-6">
            <PolicyAnalysisStep
              selectedPolicies={selectedPolicies}
              onAnalysisComplete={setAnalysisResult}
            />
            {renderBottomActions("下一步：生成大纲")}
          </div>
        )}

        {/* Step 4: Outline Generation — 雙欄：左側卡片 + 右側 sticky 面板 */}
        {currentStep === 4 && (
          <div className="flex gap-4 items-start">
            {/* 左側卡片（含大綱 + 底部按鈕） */}
            <div className="flex-1 min-w-0 bg-card rounded-xl border border-border p-6 space-y-6">
              <OutlineGenerationStep
                policyTitle={title}
                coreElements={coreElements}
                selectedPolicies={selectedPolicies}
                analysisResult={analysisResult}
                onOutlineComplete={setOutlineResult}
                draggingTitle={draggingDocTitle}
                onDragStart={setDraggingDocTitle}
                onDragEnd={() => setDraggingDocTitle(null)}
              />
              {renderBottomActions("下一步：生成政策全文")}
            </div>

            {/* 右側 sticky 參考文件面板 */}
            <ReferenceDocPanel
              policies={selectedPolicies}
              draggingTitle={draggingDocTitle}
              onDragStart={setDraggingDocTitle}
              onDragEnd={() => setDraggingDocTitle(null)}
            />
          </div>
        )}
      </motion.div>
    </div>
  );
}
